version: '3.9'
services:
  stb_backend:
    container_name: stb
    image: normanlitka/stb:0.0.1
    build:
      context: .
    ports:
      - '3001:3001'
    env_file: .env
    depends_on:
      - stb_postgres
    networks:
      - stb_network

  stb_postgres:
    container_name: stb_postgres
    hostname: stb_postgres
    image: 'postgres:13'
    ports:
      - '5431:5432'
    restart: always
    env_file: .env
    volumes:
      - bot_volume:/var/lib/postgres/data
    networks:
      - stb_network

volumes:
  bot_volume: {}

networks:
  stb_network:
    driver: bridge